/*
 * worldscale.h — world units, exporter quantisation, and the engine's physics
 *                constants.
 *
 * This header exists to keep one number in one place. Almost nothing in the
 * port should need it: work NATIVELY in world units, and reach for the scale
 * only at the boundary, when importing a reference value from PC Quake II.
 * Converting disc data to PC units at load time throws away precision and buys
 * nothing.
 *
 * ---------------------------------------------------------------------------
 * The scale itself — S = 10, INFERRED
 * ---------------------------------------------------------------------------
 * Two things about it are CONFIRMED, and they are worth separating from the
 * part that is not.
 *
 * CONFIRMED: one 64-texel texture tile spans 640 world units as the modal
 * mapping on every id-derived map — 147,872 of 279,442 full-tile edges land at
 * 640 +/- 1. So one texture texel is ten world units.
 *
 * CONFIRMED: the exporter's output lattice is generated by 10 * 2^k. Measuring
 * enrichment = P(v mod S == 0) * S over all 1,385,556 axis values on the disc
 * (points plus Scene origins), where 1.0 means "no lattice at all":
 *
 *     S     5     6     7     8     9    10    11    12    13    16    20
 *     enr  1.61  0.99  1.00  2.34  1.05  2.97  1.04  1.38  1.09  4.04  5.64
 *
 * S = 12's 1.38 is fully explained as P(mod 4) * P(mod 3) = 0.1128 against a
 * measured 0.1152 — two independent divisibilities, no 12-lattice. The
 * power-of-two rungs are shadows of the 10-family (multiples of 16 but not 80
 * are 1.4% of values; of 32 but not 160, 0.75%). So the viable set is exactly
 * {5, 10, 20}, and the tempting correspondences 216 = 18*12 (step height) and
 * 9000 = 800*11.25 (gravity) are provably coincidence.
 *
 * NOT CONFIRMED, and this is why S is marked INFERRED: the texture measurement
 * fixes ten world units per PSX TEXEL, which is one equation in two unknowns.
 * S = 10 additionally requires Hammerhead's 64x64 tiles to be 1:1 with PC Quake
 * II's 64x64 textures at texture scale 1.0. If they downsampled 128x128 sources
 * 2:1 — the standard PlayStation move — the identical measurement gives S = 5.
 * Nothing on this disc distinguishes the two. S = 20 fits the lattice slightly
 * better but makes the player's movement cube 28.6 PC units, which is not
 * credible.
 *
 * Three arguments that look like evidence and are not, recorded so nobody
 * reaches for them again:
 *
 *   - "The quantum is 10, not 5." True (residue 5 sits at 2.56%, BELOW residue
 *     4 at 2.69%, i.e. background) but scale-degenerate: every ratio internal to
 *     the PSX data is scale-invariant by construction.
 *   - "The 1280 secondary texture span would need 256x256 sources at S = 5."
 *     False. Keying textures by (map, tpage, clut, tile), 729 of 2,111 keys —
 *     34.5% — appear at two or more canonical world spans inside a single map.
 *     Texture scale is a per-surface artistic choice, not a scale invariant.
 *   - "The engine's 286-unit cube matches Quake II's 56-unit player to 2%."
 *     Numerology. The eye formula puts the eye 576 above the feet on a body 572
 *     tall, a ratio of 1.007, where PC Quake II is 46/56 = 0.82. Match the view
 *     heights instead and you get 12.5 and 13.0; match the box and you get 10.2.
 *     Two readings of the same entity disagreeing by 25% confirm nothing.
 *
 * The practical consequence: the physics constants below were RETUNED by
 * Hammerhead, not scaled from id's. Read them from the PSX executable. Never
 * derive a gameplay constant from a PC Quake II value through S.
 *
 * ---------------------------------------------------------------------------
 * Exporter quantisation — CONFIRMED
 * ---------------------------------------------------------------------------
 * stored = (int32_t)(true * S), TRUNCATED TOWARD ZERO — not floor().
 *
 * The discriminator is the sign split. |v| mod 10 peaks at residue 9 for BOTH
 * signs (36.81% of 660,601 positives, 34.58% of 708,025 negatives); floor()
 * biases negatives outward and would mirror the profile to a peak at residue 1,
 * where only 9.58% sits. A second, independent confirmation: the SIGNED offset
 * from the nearest multiple of ten is near-symmetric (-1 at 22.44% vs +1 at
 * 21.67%) while the MAGNITUDE offset is strongly inward, and only
 * round-toward-zero produces that combination.
 *
 * The error does not drift with magnitude — mean magnitude error is flat at
 * about -0.30 across |v| buckets from 100 to 25,600, four decades — so the
 * multiplier is an exact integer ratio, which rules out "S slightly less than
 * 10" as an explanation for the residue-9 dominance.
 *
 * Caveat worth knowing before trusting a snap: a single truncation of
 * grid-aligned values cannot produce the observed mass at |v| mod 10 == 1
 * (8.89%) or == 8 (10.43%), which are 3-4x the off-lattice background. About
 * 16% of vertices are genuinely off-lattice — angled brush faces intersect at
 * non-grid points. The decode rule is still right; the grid-snapping model is
 * incomplete.
 */
#ifndef Q2PSX_WORLDSCALE_H
#define Q2PSX_WORLDSCALE_H

#include "q2psx.h"

/* ------------------------------------------------------------------------- */
/* Scale                                                                      */
/* ------------------------------------------------------------------------- */

#define Q2_WORLD_PER_TEXEL   10   /* CONFIRMED: world units per texture texel  */
#define Q2_WORLD_TILE       640   /* CONFIRMED: a 64-texel tile, in world units*/
#define Q2_WORLD_GRID_UNIT   10   /* CONFIRMED: the exporter's lattice unit    */

/*
 * INFERRED. World units per PC Quake II unit. If the texel ratio is ever
 * settled (decompress a texture page, count its pixels, compare against the
 * .wal it derives from), this is the ONE line that changes. Nothing else in the
 * port should hardcode 10.
 */
#define Q2_WORLD_SCALE       10

#define Q2_PC_TO_WORLD(x)  ((x) * Q2_WORLD_SCALE)

/*
 * Recover an approximate PC-unit value from a stored world coordinate. The true
 * magnitude lies in [|v|, |v|+1) because of the inward truncation, so the
 * half-unit outward bias is the best point estimate. Do NOT apply this
 * per-vertex in the render path — the shrink is uniform and invisible.
 */
Q2PSX_INLINE float q2_world_to_pc(s32 v)
{
    return (v >= 0 ? (float)v + 0.5f : (float)v - 0.5f) * (1.0f / Q2_WORLD_SCALE);
}

/*
 * Snap a world coordinate onto an authoring grid of `grid` world units, biased
 * outward by half a unit to undo the exporter's inward truncation. grid == 10
 * recovers the lattice.
 *
 * The arithmetic runs in 64 bits deliberately: the obvious int32 form overflows
 * above 2^30 and is undefined at INT32_MIN. World coordinates never get near
 * that (the largest map spans ~78,000 units), but a tool feeding this synthetic
 * values should not be able to trip it.
 */
Q2PSX_INLINE s32 q2_world_snap(s32 v, s32 grid)
{
    s64 a;
    s32 sign;

    if (grid <= 0)
        return v;

    sign = (v < 0) ? -1 : 1;
    a    = (v < 0) ? -(s64)v : (s64)v;

    return (s32)(sign * (((2 * a + 1 + grid) / (2 * grid)) * grid));
}

/* ------------------------------------------------------------------------- */
/* Timebase                                                                   */
/* ------------------------------------------------------------------------- */
/*
 * The engine counts time in 1/300 s units on PAL. That follows from the frame
 * lock: SetVideoMode(1) gives 50 Hz fields, VSync(2) makes logic run at 25 Hz,
 * and the per-field increment is 6, so a nominal frame is 12 units.
 */
#define Q2_DT_HZ            300   /* dt units per second, PAL                  */
#define Q2_DT_PER_FIELD       6   /* gamespeed global, set at 0x80018DB8       */
#define Q2_DT_NOMINAL        12   /* 25 Hz logic                               */
#define Q2_DT_MAX            30   /* slti 31 at 0x800184B8 — a long-frame clamp*/

/* ------------------------------------------------------------------------- */
/* Physics — every immediate verified at the named instruction address         */
/* ------------------------------------------------------------------------- */

#define Q2_GRAVITY           32   /* 0x8001C7EC -> global 0x800AE924           */
#define Q2_VEL_DIV          320   /* 0x66666667 >> (32+7) at 0x80045FD8        */

/*
 * Terminal velocity. There are TWO clamps at this value, not one: 0x80046490
 * inside the secondary mover, and 0x80046084 on the player path — which an
 * earlier pass missed, having stopped reading at the store at 0x80046004 and
 * concluded the player never clamps.
 *
 * The player's clamp sits in the arm taken when the entity carries neither
 * liquid flag. An entity in liquid is governed by 0x8006FE3C easing toward
 * -3072 (buoyant, flag 0x10) or +1024 (sinking, flag 0x08) instead, and
 * genuinely never reaches the clamp.
 */
#define Q2_TERMINAL_VY     8192

/* The liquid flags at entity+0x44, set from the contents test at 0x80050CE0. */
#define Q2_ENT_LIQUID_SINK   0x08   /* contents 0x0200: eased toward +1024      */
#define Q2_ENT_LIQUID_FLOAT  0x10   /* contents 0x2000: eased toward -3072      */
#define Q2_LIQUID_SINK_VY    1024   /* @0x8004605C                              */
#define Q2_LIQUID_FLOAT_VY  -3072   /* @0x80046034                              */
#define Q2_LIQUID_BOOST     -9216   /* @0x80045948, posted when already grounded*/

/*
 * 216 sits in the DELAY SLOT of the branch at 0x80045888, so it is the DEFAULT
 * and 108 is the value taken when the entity's flags have 0x600 set. Reading
 * the two the other way round is the easy mistake here.
 */
#define Q2_STEP_HEIGHT      216
#define Q2_STEP_HEIGHT_LOW  108

/*
 * The player's half-extent, on every axis.
 *
 * This is the real hull, not a query margin — that question is now closed.
 * SecondaryCol, the hull entities move in, is PrimaryColl ERODED BY 286 on all
 * six axes: measured over 5,275 axis probes across all 115 zones, the free
 * space differs by exactly 286 in 37% of them and by 286 +/- 2 in 52%, against
 * a distribution that would be flat if the hulls were unrelated. So the box is
 * baked into the geometry and the runtime moves a point, which is why the whole
 * player call chain contains no per-entity bounds access at all.
 *
 * The entity-vs-entity sweep keeps it explicit, because the other entity moves:
 * 0x80053DA4..0x80053DFC inflates the move's AABB by it on all six faces.
 *
 * Do NOT treat this as a universal entity box. Other entities carry real mins
 * and maxs at +0x6C/+0x72, read or written 96 times across about thirty
 * functions. This one is the player's.
 */
#define Q2_SWEEP_HALF_EXTENT 286

#define Q2_VIEW_STAND        576  /* 0x8003A224                                */
#define Q2_VIEW_MID          400  /* 0x8003A214                                */
#define Q2_VIEW_CROUCH       286  /* 0x8003A228                                */
#define Q2_EYE_BASE          286  /* 0x80038638                                */

/*
 * The vertical axis is index 1 and +Y points DOWN. A larger view offset
 * therefore RAISES the camera.
 */
enum { Q2_AXIS_X = 0, Q2_AXIS_DOWN = 1, Q2_AXIS_Z = 2 };

Q2PSX_INLINE s32 q2_eye_y(s32 pos_y, s16 view_offset)
{
    return pos_y + Q2_EYE_BASE - view_offset;
}

Q2PSX_INLINE s32 q2_step_height(u32 entity_flags)
{
    return (entity_flags & 0x600u) ? Q2_STEP_HEIGHT_LOW : Q2_STEP_HEIGHT;
}

/*
 * NTSC warning. Every time-derived figure above depends on VSync(2) at 50 Hz
 * giving one dt unit == 1/300 s. The world scale is a pure length ratio and is
 * unaffected, but gravity, terminal velocity and step timing must be re-read
 * from an NTSC executable before a port claims NTSC support.
 */

#endif /* Q2PSX_WORLDSCALE_H */
